// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tracker.Web.Data;

#nullable disable

namespace Tracker.Web.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    [Migration("20260206045343_AddChargeCodeToTimeEntry")]
    partial class AddChargeCodeToTimeEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Tracker.Web.Entities.Consolidation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BillableHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnhancementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceAreaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SourceHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EnhancementId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ServiceAreaId");

                    b.HasIndex("Status");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("Consolidations");
                });

            modelBuilder.Entity("Tracker.Web.Entities.ConsolidationSource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsolidationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PulledHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeEntryId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConsolidationId");

                    b.HasIndex("TimeEntryId");

                    b.ToTable("ConsolidationSources");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Enhancement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dependencies")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedActivityType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedLaborType")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedPriority")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimationNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfActivityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfCostCenter")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("InfEstimatedHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfLaborType")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfPriority")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfServiceLine")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InfStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RequestRaisedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReturnedHours")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("ServiceAreaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceLine")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignITReference")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpawnedFromId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW2")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW3")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW4")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW5")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW6")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW7")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW8")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW9")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAreaId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkId");

                    b.ToTable("Enhancements");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementAttachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnhancementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementId");

                    b.HasIndex("UploadedAt");

                    b.HasIndex("UploadedBy");

                    b.ToTable("EnhancementAttachments");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementContact", b =>
                {
                    b.Property<string>("EnhancementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("EnhancementId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("EnhancementContacts");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementHistory", b =>
                {
                    b.Property<string>("AuditId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AuditAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnhancementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedLaborType")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedPriority")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimatedStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimationNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfLaborType")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfPriority")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfServiceLine")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReturnedHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceAreaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceLine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW2")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW3")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW4")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW5")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW6")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW7")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW8")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW9")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditAt");

                    b.HasIndex("EnhancementId");

                    b.ToTable("EnhancementHistory");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementNotificationRecipient", b =>
                {
                    b.Property<string>("EnhancementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("EnhancementId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("EnhancementNotificationRecipients");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementResource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AllocationHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChargeCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnhancementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceAreaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("ServiceAreaId");

                    b.HasIndex("EnhancementId", "ResourceId", "ServiceAreaId");

                    b.ToTable("EnhancementResources");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementSkill", b =>
                {
                    b.Property<string>("EnhancementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .HasColumnType("TEXT");

                    b.HasKey("EnhancementId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("EnhancementSkills");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementSpoc", b =>
                {
                    b.Property<string>("EnhancementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("EnhancementId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("EnhancementSpocs");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementSponsor", b =>
                {
                    b.Property<string>("EnhancementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("EnhancementId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("EnhancementSponsors");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementTimeCategory", b =>
                {
                    b.Property<string>("EnhancementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeRecordingCategoryId")
                        .HasColumnType("TEXT");

                    b.HasKey("EnhancementId", "TimeCategoryId");

                    b.HasIndex("TimeCategoryId");

                    b.HasIndex("TimeRecordingCategoryId");

                    b.ToTable("EnhancementTimeCategories");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementTimeEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnhancementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoursJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementId");

                    b.ToTable("EnhancementTimeEntries");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EstimationBreakdown", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Contingency")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContingencyNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DesignFunctionalTechnical")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignFunctionalTechnicalNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Documentation")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentationNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnhancementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GoLiveDeploymentValidation")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoLiveDeploymentValidationNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Hypercare")
                        .HasColumnType("TEXT");

                    b.Property<string>("HypercareNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PMLead")
                        .HasColumnType("TEXT");

                    b.Property<string>("PMLeadNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RequirementsAndEstimation")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequirementsAndEstimationNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TestingSTI")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestingSTINotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TestingUAT")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestingUATNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("VendorCoordination")
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorCoordinationNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementId")
                        .IsUnique();

                    b.ToTable("EstimationBreakdowns");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EstimationBreakdownItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnhancementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hours")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPhaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementId");

                    b.HasIndex("WorkPhaseId");

                    b.HasIndex("EnhancementId", "WorkPhaseId")
                        .IsUnique();

                    b.ToTable("EstimationBreakdownItems");
                });

            modelBuilder.Entity("Tracker.Web.Entities.NamedReport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("NamedReports");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Note", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnhancementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EnhancementId");

                    b.ToTable("EnhancementNotes");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Resource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanConsolidate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasLoginAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("HasLoginAccess");

                    b.HasIndex("OrganizationType");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Tracker.Web.Entities.ResourceColumnPreference", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.Property<string>("ServiceAreaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAreaId");

                    b.HasIndex("ResourceId", "ServiceAreaId")
                        .IsUnique();

                    b.ToTable("UserColumnPreferences", (string)null);
                });

            modelBuilder.Entity("Tracker.Web.Entities.ResourceServiceArea", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("Permissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ReportsToResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceAreaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportsToResourceId");

                    b.HasIndex("ResourceId");

                    b.HasIndex("ServiceAreaId");

                    b.HasIndex("ResourceId", "ServiceAreaId")
                        .IsUnique();

                    b.ToTable("ResourceServiceAreas");
                });

            modelBuilder.Entity("Tracker.Web.Entities.ResourceSkill", b =>
                {
                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .HasColumnType("TEXT");

                    b.HasKey("ResourceId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ResourceSkills");
                });

            modelBuilder.Entity("Tracker.Web.Entities.ResourceTypeLookup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowMultiple")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnhancementColumn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResourceTypeLookups");
                });

            modelBuilder.Entity("Tracker.Web.Entities.SavedFilter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("UserId");

                    b.Property<string>("ServiceAreaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAreaId");

                    b.HasIndex("ResourceId", "ServiceAreaId");

                    b.ToTable("SavedFilters");
                });

            modelBuilder.Entity("Tracker.Web.Entities.ServiceArea", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ServiceAreas");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Skill", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceAreaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAreaId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Tracker.Web.Entities.TimeEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChargeCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ContributedHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnhancementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hours")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPhaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EnhancementId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ResourceId");

                    b.HasIndex("WorkPhaseId");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("TimeEntries");
                });

            modelBuilder.Entity("Tracker.Web.Entities.TimeRecordingCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.ToTable("TimeRecordingCategories");
                });

            modelBuilder.Entity("Tracker.Web.Entities.WorkPhase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultContributionPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(100);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ForConsolidation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("ForEstimation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("ForTimeRecording")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DisplayOrder");

                    b.ToTable("WorkPhases");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Consolidation", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Resource", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("Consolidations")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Resource", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tracker.Web.Entities.ServiceArea", "ServiceArea")
                        .WithMany()
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Enhancement");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ServiceArea");
                });

            modelBuilder.Entity("Tracker.Web.Entities.ConsolidationSource", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Consolidation", "Consolidation")
                        .WithMany("Sources")
                        .HasForeignKey("ConsolidationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.TimeEntry", "TimeEntry")
                        .WithMany("ConsolidationSources")
                        .HasForeignKey("TimeEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consolidation");

                    b.Navigation("TimeEntry");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Enhancement", b =>
                {
                    b.HasOne("Tracker.Web.Entities.ServiceArea", "ServiceArea")
                        .WithMany("Enhancements")
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceArea");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementAttachment", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("Attachments")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Resource", "UploadedByResource")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Enhancement");

                    b.Navigation("UploadedByResource");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementContact", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("Contacts")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany("EnhancementContacts")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enhancement");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementNotificationRecipient", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("NotificationRecipients")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enhancement");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementResource", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("Resources")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany("EnhancementResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enhancement");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementSkill", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("Skills")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Skill", "Skill")
                        .WithMany("EnhancementSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enhancement");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementSpoc", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("Spocs")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany("EnhancementSpocs")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enhancement");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementSponsor", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("Sponsors")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany("EnhancementSponsors")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enhancement");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementTimeCategory", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("TimeCategories")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.TimeRecordingCategory", "TimeCategory")
                        .WithMany()
                        .HasForeignKey("TimeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.TimeRecordingCategory", null)
                        .WithMany("EnhancementTimeCategories")
                        .HasForeignKey("TimeRecordingCategoryId");

                    b.Navigation("Enhancement");

                    b.Navigation("TimeCategory");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementTimeEntry", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("TimeEntries")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enhancement");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EstimationBreakdown", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithOne("EstimationBreakdown")
                        .HasForeignKey("Tracker.Web.Entities.EstimationBreakdown", "EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enhancement");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EstimationBreakdownItem", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("EstimationBreakdownItems")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.WorkPhase", "WorkPhase")
                        .WithMany("EstimationItems")
                        .HasForeignKey("WorkPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Enhancement");

                    b.Navigation("WorkPhase");
                });

            modelBuilder.Entity("Tracker.Web.Entities.NamedReport", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Note", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Resource", "CreatedByResource")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("NoteHistory")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByResource");

                    b.Navigation("Enhancement");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Resource", b =>
                {
                    b.HasOne("Tracker.Web.Entities.ResourceTypeLookup", "ResourceType")
                        .WithMany("Resources")
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("Tracker.Web.Entities.ResourceColumnPreference", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.ServiceArea", "ServiceArea")
                        .WithMany()
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("ServiceArea");
                });

            modelBuilder.Entity("Tracker.Web.Entities.ResourceServiceArea", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Resource", "ReportsTo")
                        .WithMany()
                        .HasForeignKey("ReportsToResourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany("ServiceAreas")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.ServiceArea", "ServiceArea")
                        .WithMany()
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportsTo");

                    b.Navigation("Resource");

                    b.Navigation("ServiceArea");
                });

            modelBuilder.Entity("Tracker.Web.Entities.ResourceSkill", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany("Skills")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Skill", "Skill")
                        .WithMany("ResourceSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Tracker.Web.Entities.SavedFilter", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.ServiceArea", "ServiceArea")
                        .WithMany()
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("ServiceArea");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Skill", b =>
                {
                    b.HasOne("Tracker.Web.Entities.ServiceArea", "ServiceArea")
                        .WithMany()
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceArea");
                });

            modelBuilder.Entity("Tracker.Web.Entities.TimeEntry", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Resource", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("TimeEntriesNew")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Resource", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany("TimeEntries")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.WorkPhase", "WorkPhase")
                        .WithMany("TimeEntries")
                        .HasForeignKey("WorkPhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Enhancement");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Resource");

                    b.Navigation("WorkPhase");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Consolidation", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Enhancement", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Consolidations");

                    b.Navigation("Contacts");

                    b.Navigation("EstimationBreakdown");

                    b.Navigation("EstimationBreakdownItems");

                    b.Navigation("NoteHistory");

                    b.Navigation("NotificationRecipients");

                    b.Navigation("Resources");

                    b.Navigation("Skills");

                    b.Navigation("Spocs");

                    b.Navigation("Sponsors");

                    b.Navigation("TimeCategories");

                    b.Navigation("TimeEntries");

                    b.Navigation("TimeEntriesNew");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Resource", b =>
                {
                    b.Navigation("EnhancementContacts");

                    b.Navigation("EnhancementResources");

                    b.Navigation("EnhancementSpocs");

                    b.Navigation("EnhancementSponsors");

                    b.Navigation("ServiceAreas");

                    b.Navigation("Skills");

                    b.Navigation("TimeEntries");
                });

            modelBuilder.Entity("Tracker.Web.Entities.ResourceTypeLookup", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("Tracker.Web.Entities.ServiceArea", b =>
                {
                    b.Navigation("Enhancements");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Skill", b =>
                {
                    b.Navigation("EnhancementSkills");

                    b.Navigation("ResourceSkills");
                });

            modelBuilder.Entity("Tracker.Web.Entities.TimeEntry", b =>
                {
                    b.Navigation("ConsolidationSources");
                });

            modelBuilder.Entity("Tracker.Web.Entities.TimeRecordingCategory", b =>
                {
                    b.Navigation("EnhancementTimeCategories");
                });

            modelBuilder.Entity("Tracker.Web.Entities.WorkPhase", b =>
                {
                    b.Navigation("EstimationItems");

                    b.Navigation("TimeEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
