// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tracker.Web.Data;

#nullable disable

namespace Tracker.Web.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    partial class TrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Tracker.Web.Entities.Enhancement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimationNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfServiceLine")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InfStatus")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReturnedHours")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("ServiceAreaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceLine")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW2")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW3")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW4")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW5")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW6")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW7")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW8")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW9")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAreaId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkId");

                    b.ToTable("Enhancements");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementContact", b =>
                {
                    b.Property<string>("EnhancementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("EnhancementId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("EnhancementContacts");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementHistory", b =>
                {
                    b.Property<string>("AuditId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditAction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AuditAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnhancementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedEndDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EstimatedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstimationNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfServiceLine")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ReturnedHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceAreaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceLine")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW1")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW2")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW3")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW4")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW5")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW6")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW7")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW8")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TimeW9")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditAt");

                    b.HasIndex("EnhancementId");

                    b.ToTable("EnhancementHistory");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementResource", b =>
                {
                    b.Property<string>("EnhancementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("EnhancementId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("EnhancementResources");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementSpoc", b =>
                {
                    b.Property<string>("EnhancementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("EnhancementId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("EnhancementSpocs");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementSponsor", b =>
                {
                    b.Property<string>("EnhancementId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("EnhancementId", "ResourceId");

                    b.HasIndex("ResourceId");

                    b.ToTable("EnhancementSponsors");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EstimationBreakdown", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Contingency")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContingencyNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DesignFunctionalTechnical")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignFunctionalTechnicalNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Documentation")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentationNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnhancementId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GoLiveDeploymentValidation")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoLiveDeploymentValidationNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Hypercare")
                        .HasColumnType("TEXT");

                    b.Property<string>("HypercareNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PMLead")
                        .HasColumnType("TEXT");

                    b.Property<string>("PMLeadNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RequirementsAndEstimation")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequirementsAndEstimationNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TestingSTI")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestingSTINotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TestingUAT")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestingUATNotes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("VendorCoordination")
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorCoordinationNotes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnhancementId")
                        .IsUnique();

                    b.ToTable("EstimationBreakdowns");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Resource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Tracker.Web.Entities.SavedFilter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceAreaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAreaId");

                    b.HasIndex("UserId", "ServiceAreaId");

                    b.ToTable("SavedFilters");
                });

            modelBuilder.Entity("Tracker.Web.Entities.ServiceArea", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ServiceAreas");
                });

            modelBuilder.Entity("Tracker.Web.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tracker.Web.Entities.UserColumnPreference", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ColumnsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceAreaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAreaId");

                    b.HasIndex("UserId", "ServiceAreaId")
                        .IsUnique();

                    b.ToTable("UserColumnPreferences");
                });

            modelBuilder.Entity("Tracker.Web.Entities.UserServiceArea", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceAreaId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "ServiceAreaId");

                    b.HasIndex("ServiceAreaId");

                    b.ToTable("UserServiceAreas");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Enhancement", b =>
                {
                    b.HasOne("Tracker.Web.Entities.ServiceArea", "ServiceArea")
                        .WithMany("Enhancements")
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceArea");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementContact", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("Contacts")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany("EnhancementContacts")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enhancement");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementResource", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("Resources")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany("EnhancementResources")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enhancement");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementSpoc", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("Spocs")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany("EnhancementSpocs")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enhancement");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EnhancementSponsor", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithMany("Sponsors")
                        .HasForeignKey("EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.Resource", "Resource")
                        .WithMany("EnhancementSponsors")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enhancement");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Tracker.Web.Entities.EstimationBreakdown", b =>
                {
                    b.HasOne("Tracker.Web.Entities.Enhancement", "Enhancement")
                        .WithOne("EstimationBreakdown")
                        .HasForeignKey("Tracker.Web.Entities.EstimationBreakdown", "EnhancementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enhancement");
                });

            modelBuilder.Entity("Tracker.Web.Entities.SavedFilter", b =>
                {
                    b.HasOne("Tracker.Web.Entities.ServiceArea", "ServiceArea")
                        .WithMany()
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceArea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tracker.Web.Entities.UserColumnPreference", b =>
                {
                    b.HasOne("Tracker.Web.Entities.ServiceArea", "ServiceArea")
                        .WithMany()
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceArea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tracker.Web.Entities.UserServiceArea", b =>
                {
                    b.HasOne("Tracker.Web.Entities.ServiceArea", "ServiceArea")
                        .WithMany("UserServiceAreas")
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Web.Entities.User", "User")
                        .WithMany("ServiceAreas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceArea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Enhancement", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("EstimationBreakdown");

                    b.Navigation("Resources");

                    b.Navigation("Spocs");

                    b.Navigation("Sponsors");
                });

            modelBuilder.Entity("Tracker.Web.Entities.Resource", b =>
                {
                    b.Navigation("EnhancementContacts");

                    b.Navigation("EnhancementResources");

                    b.Navigation("EnhancementSpocs");

                    b.Navigation("EnhancementSponsors");
                });

            modelBuilder.Entity("Tracker.Web.Entities.ServiceArea", b =>
                {
                    b.Navigation("Enhancements");

                    b.Navigation("UserServiceAreas");
                });

            modelBuilder.Entity("Tracker.Web.Entities.User", b =>
                {
                    b.Navigation("ServiceAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
